### ISSUE TITLE
BE: Pet Store

### ISSUE THREAD

**Issue by moffatethan** [hatchways/team-naan-bread#94]
I would like companies to be able to sign up and sell products on the platform, let's setup the back-end for this right now. Below are the specifications

- A user owns a Company
- A company owns Products
- Products have reviews, prices, and stock.

Create schemas for Company and Product, below are the structure. Note, they might need more properties than listed.

Company
- name
- owner
- products
- reviews
- timestamps

Product
- name
- description (markdown)
- stock
- price
- company
- timestamps

**Comment by lipob** [comment]
Hi @moffatethan Timestamps options are generated by default, right? Or do you need to implement something customized?

Edit: 
I added { timestamps: true }

**Comment by lipob** [comment]
I added { timestamps: true  }
